config/routes.rb
Node::Application.routes.draw do

  # 首页
  root to: 'static_pages#home'
  
  # github登录
  match "/auth/:provider/callback", :to => 'omniauths#create'

  #发布内容，评论
  resources :posts do
    # 评论
    resources :comments

    member do
      # 文章收藏功能
      # get :favorite
      # 赞功能
      # get :zan
      # 文章收藏，赞功能
      get :topic_function
    end
    
    # 标签
    collection do
      # 文章种类
      get 'post_kind'
    end

  end 

  # 用户关系
  resources :relationships, only: [ :create, :destroy ]

  # 用户登录
  resources :sessions, only: [ :new, :create, :destroy ]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  # 首页登录出错跳转
  match '/sessions', to: 'sessions#new'
  
  # 找回密码
  resources :password_resets
  # 重置密码
  get 'password_resets/new'
  

  # 站内通知
  resources :notifications 

  # 管理员功能
  namespace :admins do
    resources :users
  end 

  # 用户系统
  resources :users do

    member do
      # 用户关注
      get :following, :followers
      # 文章收藏(喜爱)
      get :favorite
      # 签到
      get :qiandao
      get :qiandao_execute
      # 设置管理员
      get :set_admin
    end

    collection do
      # qq登录
      get :qqlogin
    end
  end
end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :website, :github,
                  :twitter, :qq, :city, :company, :position, :autograph, :resume,
                  :avatar, :avatar_cache, :favorite_topic_ids, :zan_topic_ids
  # 安全密码
  has_secure_password

  # 发表文章
  has_many :posts, dependent: :destroy

  # 评论列表
  has_many :comments, dependent: :destroy

  # 第三方登录
  has_many :authentications

  # 上传文件(头像)
  mount_uploader :avatar, AvatarUploader

  # 站内通知提醒
  has_many :notifications, dependent: :destroy

  # 签到功能
  has_many :qiandaos, dependent: :destroy

  # 用户关注
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
              class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  # 存入数据库之前
  before_save { |user| user.email = email.downcase }
  before_save { |user| user.name = name.downcase }
  before_create { create_remember_token(:remember_token) }
  before_save { github_url }
  before_save { twitter_url }
  before_save { website_url }
  # 如果首次收藏文章把nil变成空字符串
  before_save { self.favorite_topic_ids = " " if self.favorite_topic_ids == nil }
  before_save { self.zan_topic_ids = " " if self.zan_topic_ids == nil }

  # 用户身份验证
  # validates :name, presence: true, length: { maximum: 50 }
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true,
  #                   format: { with: VALID_EMAIL_REGEX },
  #                   uniqueness: { case_sensitive: false }
  # validates :password, presence: true, length: { minimum: 6 }, :if => :new_record?
  # validates :password_confirmation, presence: true, :if => :new_record?
  validates_presence_of :name, :email, :password, :password_confirmation, 
                        message: "不能为空!", if: :new_record? #password reset bug
  validates_length_of :name, :password, in: 1..20, message: "必须为1到20的字符!",
                        if: :new_record? #password reset bug
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, with: VALID_EMAIL_REGEX, message: "格式不正确!"
  validates_uniqueness_of :email, :name, case_sensitive: false, message: "已存在!"

  # 用户资料验证
  validates_numericality_of :qq, only_integer: true, allow_nil: true, message: "必须是整数!"


  # 发送密码找回邮件
  def send_password_reset
    create_remember_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end


  # 用户关注
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end


  # 格式验证
  def github_url
    return "" if self.github.blank?
    "https://github.com/#{self.github.split('/').last}"
  end
  def twitter_url
    return "" if self.twitter.blank?
    "https://twitter.com/#{self.twitter}"
  end
  def website_url
    return "" if self.website.blank?
    "http://#{self.website}"
  end


  # 第三方登录(github)
  class << self
    # 判断用户是否存在
    def from_auth(auth)
      locate_auth(auth) || create_auth(auth)
    end
    # 查找用户
    def locate_auth(auth)
      Authentication.find_by_provider_and_uid(auth[:provider], auth[:uid]).try(:user)
    end
    # 创建新用户
    def create_auth(auth)
      User.new do |user|
        user.name = auth[:info][:nickname]
        user.email = auth[:info][:email]
        # 提取头像并设置头像
        # user.avatar = auth[:info][:image]
        # 生成无用的密码保护
        user.password_digest = "#{SecureRandom.urlsafe_base64}"
        # user.auth_token = auth[:token]
        user.authentications.build do |authentication|
          authentication.provider = auth[:provider]
          authentication.uid = auth[:uid]
          authentication.save
        end
         user.save!(validate: false)
      end
    end
  end


  # # 收藏功能
  # def favorite_topic(post_id)
  #   return false if post_id.blank?
  #   return false if self.favorite_topic_ids.include?(post_id)
  #   # 把文章id存入数据库
  #   post_ids = self.favorite_topic_ids.insert(1, ",#{post_id}")
  #   # 测试post_ids是否正确
  #   # logger.debug { "---#{post_ids}" }
  #   self.update_attribute(:favorite_topic_ids, "1")   # 不使用这句无法将数据存入数据库
  #   self.update_attribute(:favorite_topic_ids, post_ids)
  # end
  # # 取消收藏
  # def unfavorite_topic(post_id)
  #   return false if post_id.blank?
  #   # 删除选中的文章id
  #   post_ids = self.favorite_topic_ids.split(",")
  #   post_ids.delete "#{post_id}"
  #   post_ids_result = post_ids.join(",")
  #   # 测试post_ids_result是否正确
  #   # logger.debug { "---#{post_ids_result}" }
  #   self.update_attribute(:favorite_topic_ids, post_ids_result)
  # end

  # # 赞功能
  # def zan_topic(post_id)
  #   return false if post_id.blank?
  #   return false if self.zan_topic_ids.include?(post_id)
  #   # 把文章id存入数据库
  #   post_ids = self.zan_topic_ids.insert(1, ",#{post_id}")
  #   self.update_attribute(:zan_topic_ids, "1")
  #   self.update_attribute(:zan_topic_ids, post_ids)
  # end
  # # 已赞
  # def yizan_topic(post_id)
  #   return false if post_id.blank?
  #   # 删除选中的文章id
  #   post_ids = self.zan_topic_ids.split(",")
  #   post_ids.delete "#{post_id}"
  #   post_ids_result = post_ids.join(",")
  #   self.update_attribute(:zan_topic_ids, post_ids_result)
  # end

  # 文章操作(收藏，赞)
  def operate_topic(post_id, topic_ids, type)
    return false if post_id.blank?
    return false if topic_ids.include?(post_id)
    # 把文章id存入数据库
    post_ids = topic_ids.insert(1, ",#{post_id}")
    self.update_attribute(type, "1")
    self.update_attribute(type, post_ids)
  end
  # 取消
  def cancel_topic(post_id, topic_ids, type)
    return false if post_id.blank?
    # 删除选中的文章id
    post_ids = topic_ids.split(",")
    post_ids.delete "#{post_id}"
    post_ids_result = post_ids.join(",")
    self.update_attribute(type, post_ids_result)
  end


  private
    # 创建密码保护
    def create_remember_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
    end
end

app/controllers/admins/users_controller.rb
#encoding: utf-8
class Admins::UsersController < ApplicationController
  def index
    @admins = User.where(admin: true)
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  before_filter :correct_user, only: [ :edit, :update ]
  before_filter :signed_in_user,
                only: [ :index, :edit, :update, :destroy, :following, :followers, :favorite ]
  before_filter :admin, only: :destroy

  def index
    @users = User.page(params[:page])
    @super_admin = User.find(1)
  end

  def show
    @user = User.find(params[:id])
    @super_admin = User.find(1)
    @posts = @user.posts.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      sign_in @user
      # 注册邮件提醒
      SignupMailer.send_signup_mailer(@user).deliver
      flash[:success] = "Welcome #{@user.name}"
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # if params[:user][:password].blank?
    #   params[:user].delete(:password)
    #   params[:user].delete(:password_confirmation)
    # end
    if @user.update_attributes(params[:user])
      flash[:success] = "更新资料成功!"
      sign_in @user
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "用户已删除"
    redirect_to users_path
  end

  # 显示关注
  def following
    @title = "关注"
    @user = User.find(params[:id])
    @users = @user.followed_users.page(params[:page]).per_page(12)
    render 'show_follow'
  end

  # 显示粉丝
  def followers
    @title = "粉丝"
    @user = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per_page(12)
    render 'show_follow'
  end

  # QQ登录
  def qqlogin
    redirect_to Qq.redo("get_user_info")
  end

  # 显示收藏的文章
  def favorite
    @favorite_posts = Post.where(id: current_user.favorite_topic_ids.split(","))
  end

  # 签到功能
  def qiandao
    # 如果数据库没有签到数据则创建一条防止nil
    if current_user.qiandaos == []
      current_user.qiandaos.create(qiandao_day_count: 0, qiandao_day_time: 0)
    end
    @qiandao_day_count = current_user.qiandaos.last.qiandao_day_count
    @is_qiandao = Time.now.strftime('%m%d').to_i - current_user.qiandaos.last.qiandao_day_time
    render 'qiandao_execute'
  end
  # 执行签到功能
  def qiandao_execute
    @qiandao_day_count = current_user.qiandaos.last.qiandao_day_count
    @is_qiandao = Time.now.strftime('%m%d').to_i - current_user.qiandaos.last.qiandao_day_time

    now_time = Time.now.strftime('%m%d').to_i
    continuous_day = now_time. - current_user.qiandaos.last.qiandao_day_time
    # 用时间判断是否连续签到
    if continuous_day == 1
      # 昨天签过到
      qiandao_day_count = current_user.qiandaos.last.qiandao_day_count + 1
      current_user.qiandaos.create(qiandao_day_count: qiandao_day_count, qiandao_day_time: now_time)
    elsif continuous_day == 0
      # 连续点击签到无效
      flash[:error] = "今天已经签到了哦!"
    else
      # 没有连续签到或首次签到
      current_user.qiandaos.create(qiandao_day_count: 1, qiandao_day_time: now_time)
    end
    redirect_to qiandao_user_path(current_user)
  end


  # 超级管理员设置管理员
  def set_admin
    user = User.find(params[:id])
    if user.toggle!(:admin)
      redirect_to user
    else
      flash[:error] = "设置失败！"
      redirect_to root_path
    end
  end

  private
    # 用户只能修改自己的资料
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
	# # 用户头像
	# def gravatar_for(user, options = { size: 50 })
	# 	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	# 	size = options[:size]
	# 	gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png?s=#{size}"
	# 	image_tag(gravatar_url, alt: user.name, class: "gravatar")
	# end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "关注", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
	  <% if current_user.following?(@user) %>
	    <%= render 'unfollow' %>
	  <% else %>
	    <%= render 'follow' %>
	  <% end %>
	</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "取消关注", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li class="follow-list-item">
	<%= link_to image_tag(@user.avatar_url(:small)), user if @user.avatar? %>
	<%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<div id="page_main">
	<div class="user_edit_main">
		<h3>个人资料设置</h3>
		<div class="line"></div>
		<div class="user_edit_form">
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages' %>

			<!-- 	<div class="input-prepend"> -->
				<%= f.label :name, "名字", class: "label" %>
				<%= f.text_field :name, disabled: "disabled", class: "uneditable-input" %> </br>
			<!-- 	<div/> -->

				<%= f.label :portrait, "头像", class: "label" %>
				<%= image_tag(@user.avatar_url(:thumb)) if @user.avatar? %>
				<%= f.file_field :avatar %>
				<%= f.hidden_field :avatar_cache %> </br>

			<!-- 	<div class="input-prepend"> -->
				<%= f.label :email, "电子邮件", class: "label" %>
				<%= f.text_field :email, disabled: "disabled", class: "uneditable-input" %> </br>
			<!-- 	<div/> -->

			<!-- 	<div class="input-prepend"> -->
				<%= f.label :website, "个人网站", class: "label" %>
				<span class="add-on">http://</span>
				<%= f.text_field :website, placeholder: "http://" %> </br>
			<!-- 	</div> -->

			<!-- 	<div class="input-prepend"> -->
				<%= f.label :github, "Github", class: "label" %>
				<span class="add-on">https://github.com/</span>
				<%= f.text_field :github, placeholder: "Username" %> </br>
			<!-- 	</div> -->

				<!-- <div class="input-prepend"> -->
				<%= f.label :twitter, "Twitter", class: "input-prepend label" %>
				<span class="add-on">http://twitter.com/</span>
				<%= f.text_field :twitter, placeholder: "Username" %> </br>
			<!-- 	<div/> -->

				<%= f.label :qq, "QQ", class: "label" %>
				<%= f.text_field :qq %> </br>

				<%= f.label :city, "城市", class: "label" %>
				<%= f.text_field :city %> </br>

				<%= f.label :company, "学校or公司", class: "label" %>
				<%= f.text_field :company %> </br>

				<%= f.label :position, "职位", class: "label" %>
				<%= f.text_field :position %> </br>

				<%= f.label :autograph, "签名", class: "label" %>
				<%= f.text_field :autograph %> </br>

				<%= f.label :resume, "个人简介", class: "label" %>
				<%= f.text_area :resume, class: "resume" %> </br>

				
				<%= f.submit "更新资料", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
	<%= render 'shared/tips' %>
	<!-- 清除浮动 -->
	<div class="class"></div>
</div>

app/views/users/favorite.html.erb
<h3>我的收藏</h3>
<% @favorite_posts.each do |favorite_post| %>
  <h4><%= link_to favorite_post.title, favorite_post %></h4>
  <p><%= truncate(strip_tags(favorite_post.content), length: 100) %><p/>
<% end %>

app/views/users/index.html.erb
<div class="index_users">
	<h4>目前已经有 <%= @users.all.count %> 位会员加入了share</h4>
	<ol class="follow-list">
		<% @users.each do |user| %>
			<li class="follow-list-item">
				<!-- 显示用户上传头像，否则显示默认头像 -->
				<%= user.avatar? ? link_to(image_tag(user.avatar_url(:small)), user) : link_to(image_tag("uu.jpg", :height => '100', :width => '100'), user) %>
				<%= link_to user.name, user %>
				<!-- <p>加入时间: <%= user.created_at.strftime('%F') %></p> -->
				<!-- 当前用户是管理员，不能删除自己，不能删除超级管理员 -->
				<% if current_user.admin? && !current_user?(user) && user!=@super_admin %>
    			<%= link_to("删除", user, method: :delete, data: { confirm: "删除此用户?" }) %>
        <% end %>
			</li>
		<% end %>
	</ol>
	<!-- 清除浮动 -->
	<div class="class"></div>
</div>
<%= will_paginate %>

app/views/users/new.html.erb
<h3>注册</h3>
<div class="signup">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>

		<%= f.label :email, "电子邮件地址" %>
		<%= f.text_field :email %>
	    <span>还没有填写邮箱</span>

		<%= f.label :password, "创建密码" %>
		<%= f.password_field :password %>
		<span>输入的6-20个字符作为登陆密码</span>

		<%= f.label :password_confirmation, "确认密码" %>
		<%= f.password_field :password_confirmation %>
		<span>输入与上面密码相同的字符</span>

		<%= f.label :name, "选择你的用户名" %>
	    <%= f.text_field :name %>
	    <span>起一个个性的名字吧!</span>

	    <br/>
	    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
	    <%= label_tag :remember_me, "下次自动登录" %>
		<%= f.submit "创建我的帐号", class: "btn btn-large btn-primary" %>

	<% end %>
</div>

app/views/users/qiandao_execute.html.erb
<% if @is_qiandao == 0 %>
  <%= link_to "今天已签到", controller: 'users', action: 'qiandao_execute' %></br>
<% else %>
  <%= link_to "签到", controller: 'users', action: 'qiandao_execute' %></br>
<% end %>
已连续签到 <%= @qiandao_day_count %> 天

app/views/users/show.html.erb
<!-- 用户资料显示 -->
<div class="show_user">
	<div class="user_info_main">
		第<%= @user.id %>号会员  <br/>
		名字: <%= @user.name %> <br/>
		Email: <%= @user.email %> <br/>

		<% if !@user.website.blank? %>
			博客:   <%= link_to @user.website, @user.website_url %> <br/>
		<% end %>

		<% if !@user.github.blank? %>
			Github: <%= link_to @user.github, @user.github_url %> <br/>
		<% end %>

		<% if !@user.twitter.blank? %>
			Twitter:  <%= link_to @user.twitter, @user.twitter_url %> <br/>
		<% end %>

		<% if !@user.qq.blank? %>
			QQ: <%= @user.qq %> <br/>
		<% end %>

		<% if !@user.city.blank? %>
			城市: <%= @user.city %> <br/>
		<% end %>

		<% if !@user.company.blank? %>
			公司: <%= @user.company %> <br/>
		<% end %>

		<% if !@user.position.blank? %>
			职位: <%= @user.position %> <br/>
		<% end %>

		<% if !@user.autograph.blank? %>
			签名: <%= @user.autograph %> <br/>
		<% end %>

		加入时间: <%= @user.created_at.strftime('%F') %> <br/>

		<% if !@user.resume.blank? %>
			个人简介: <%= @user.resume %>
		<% end %>

		<section>
			<%= render 'shared/stats' %>
		</section>
	</div>

	<div class="follow_button">
		<!-- 显示是否是管理员 -->
		<% if @user.admin? %>
			管理员
		<% end %>
		<!-- 超级管理员可以设置其他用户为管理员 -->
		<!-- 当前用户是否为超级管理员，选择用户是管理员，不能取消超级管理员 -->
		<% if current_user?(@super_admin) && @user.admin? && !current_user?(@user) %>
			<%= link_to "取消管理员", set_admin_user_path(@user) %>
		<% end %>
		<!-- 当前用户是否为超级管理员，选择用户不是管理员 -->
		<% if current_user?(@super_admin) && !@user.admin? %>
			<%= link_to "设为管理员", set_admin_user_path(@user) %>
		<% end %>
		<!-- 显示用户上传头像，否则显示默认头像 -->
		<%= @user.avatar? ? image_tag(@user.avatar_url(:thumb)) : image_tag("uu.jpg", :height => '100', :width => '100') %>
		<!-- 显示关注数量列表 -->
	  <%= render 'follow_form' if signed_in? %>
	</div>

	<div class="class"></div>
</div>
<!-- 显示该用户发布的文章 -->
<div>
	<h3>我发表的文章</h3>
	<% @posts.each do |post| %>
		文章标题<%= link_to post.title, post_path(post) %>
		共<%= post.comments.count %>条回复
		<!-- 删除链接 -->
		<% if current_user?(post.user) %>
			<%= link_to "删除", post, method: :delete, data: { confirm: "确定要删除吗?" } %>  <br/>
		<% end %>
	<% end %>
</div>
<!-- 显示该用户评论过的文章 -->
<div>
	<h3>我发表的评论</h3>
	<% @user.comments.each do |comment| %>
		文章标题<%= link_to comment.post.title, post_path(comment.post) %>
		评论内容<%= comment.body %>  <br/>
	<% end %>
</div>
 

app/views/users/show_follow.html.erb
<div class="follow_main">
	<h2>
		<%= @title %>
	</h2>
	<div class="container">
		<% if @users.any? %>
			<ol class="follow-list">
				<%= render @users %>
			</ol>
			<%= will_paginate %>
		<% end %>
	</div>
</div>