config/routes.rb
Node::Application.routes.draw do

  # 首页
  root to: 'static_pages#home'
  
  # github登录
  match "/auth/:provider/callback", :to => 'omniauths#create'

  #发布内容，评论
  resources :posts do
    # 评论
    resources :comments

    member do
      # 文章收藏功能
      # get :favorite
      # 赞功能
      # get :zan
      # 文章收藏，赞功能
      get :topic_function
    end
    
    # 标签
    collection do
      # 文章种类
      get 'post_kind'
    end

  end 

  # 用户关系
  resources :relationships, only: [ :create, :destroy ]

  # 用户登录
  resources :sessions, only: [ :new, :create, :destroy ]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  # 首页登录出错跳转
  match '/sessions', to: 'sessions#new'
  
  # 找回密码
  resources :password_resets
  # 重置密码
  get 'password_resets/new'
  

  # 站内通知
  resources :notifications 

  # 管理员功能
  namespace :admins do
    resources :users
  end 

  # 用户系统
  resources :users do

    member do
      # 用户关注
      get :following, :followers
      # 文章收藏(喜爱)
      get :favorite
      # 签到
      get :qiandao
      get :qiandao_execute
      # 设置管理员
      get :set_admin
    end

    collection do
      # qq登录
      get :qqlogin
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	attr_accessible :content, :title, :kind

	has_many :comments, dependent: :destroy

	belongs_to :user

	validates :user_id, presence: true
	validates :title, presence: true, length: { maximum: 50 }
	validates :content, presence: true, length: { maximum: 900 }
	validates :kind, presence: true, inclusion: { in: %w(node blog suibi log news acm activity tool) }

	default_scope order: 'posts.created_at DESC'

	# 全文搜索
	# searchable do 
	# 	text :title, :content
	# 	text :comments do
	# 		comments.map { |comment| comment.body }
	# 	end
	# end

	#浏览计算器
	def increment(attribute, by = 1)
		self[attribute] ||= 0
		self[attribute] += by
		self.save
	end

end

app/controllers/posts_controller.rb
#encoding: utf-8
class PostsController < ApplicationController
	before_filter :signed_in_user, only: [ :create, :destroy, :favorite ]
	before_filter :correct_user, only: :destroy

	# 全文搜索
	# def index
	# 	if params[:search].blank?
	# 		flash[:error] = "请输入您要查找的内容！"
	# 		redirect_to root_path
	# 	else
	# 		@search = Post.search do 
	# 			fulltext params[:search]
	# 		end
	# 		@posts = @search.results
	# 	end
	# end

	def show
		@post = Post.find(params[:id])
		#浏览计数器
		@post.increment(:viewed_count)   
		@comments = @post.comments.compact                    
		@comment = @post.comments.build
	end

	def new
		@post = current_user.posts.build
	end

	def create
		# 给文章打上标签方便检索
		@post = current_user.posts.build(title: params[:post][:title], content: params[:post][:content], kind: session[:kind])
		if @post.save
		  redirect_to post_path(@post)
		else
			# 如果文章没有保存成功则删除session
			session[:kind] = nil
			flash.now[:error] = "文章不符合标准哦！"
			render 'post_kind'
		end
	end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to @post
    else
      render 'edit'
    end
  end

	# 文章种类的确定
	def post_kind
		@post = current_user.posts.build
		# 用户选择了文章类型
		if params[:kind]
			# 使用session保存kind
			session[:kind] = "#{params[:kind]}"
	 		render 'new' 
	 	else
	 		render 'post_kind'
	 	end
	end

  # 文章收藏(喜爱)
  # def favorite
  #   if(current_user.favorite_topic_ids.include?(params[:id].to_s))
  #     current_user.unfavorite_topic(params[:id])
  #   else
  #     current_user.favorite_topic(params[:id])
  #   end

  #   redirect_to post_path(params[:id])
  # end

  # # 赞文章
  # def zan
  # 	if(current_user.zan_topic_ids.include?(params[:id].to_s))
  # 		current_user.yizan_topic(params[:id])
  # 	else
  # 		current_user.zan_topic(params[:id])
  # 	end

  # 	redirect_to post_path(params[:id])
  # end

  def topic_function
  	# 根据传入的值判断操作
	 	if params[:function_chose] == "favorite_topic_ids"
	 		topic_ids = current_user.favorite_topic_ids
	 		type = "favorite_topic_ids"
	 	else
	 		topic_ids = current_user.zan_topic_ids
	 		type = "zan_topic_ids"
	 	end	
    # 根据是否关注(赞)选择方法
 		if(topic_ids.include?(params[:id].to_s))
      current_user.cancel_topic(params[:id], topic_ids, type)
    else
      current_user.operate_topic(params[:id], topic_ids, type)
    end

    redirect_to post_path(params[:id])
  end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	private 
		def correct_user
			@post = Post.find(params[:id])
			redirect_to root_path if @post.nil?
		end

end

app/helpers/posts_helper.rb
module PostsHelper

  # 文章收藏
  # def topic_favorite_tag(topic)
  #   return "" if current_user.blank?
  #   link_title = "收藏"
  #   if current_user && current_user.favorite_topic_ids.include?(topic.id.to_s)
  #     link_title = "取消收藏"
  #   end

  #   link_to "#{link_title}", controller: 'posts', action: 'favorite'
  # end

  # def topic_zan_tag(topic)
  #   return "" if current_user.blank?
  #   link_title = "赞"
  #   if current_user && current_user.zan_topic_ids.include?(topic.id.to_s)
  #     link_title = "已赞"
  #   end

  #   link_to "#{link_title}", controller: 'posts', action: 'zan'
  # end

  # 文章功能
  def topic_function_tag(topic, function_topic_ids, *link_title_chose)
    return "" if current_user.blank?
    link_title = link_title_chose[0]
    # 根据传入的值判断操作
    topic_ids = function_topic_ids == 'favorite_topic_ids' ? current_user.favorite_topic_ids : current_user.zan_topic_ids
    if current_user && topic_ids.include?(topic.id.to_s)
      link_title = link_title_chose[1]
    end

    link_to "#{link_title}", controller: 'posts', action: 'topic_function', function_chose: "#{function_topic_ids}"
  end
end

app/views/posts/edit.html.erb
<div id="page_main">
  <div class="post_main">
    <div class="post_title">
      <%= form_for(@post) do |f| %>
        
        <%= f.label :title, "主题" %>
        <%= f.text_field :title, class: "input-xxlarge" %>

        <%= f.label :content, "内容" %>
        <%= f.text_area :content, class: "textarea" %>

        <%= f.select(:kind, [['笔记', 'node'], ['博客', 'blog'], ['随笔', 'suibi'], ['日志', 'log'],
                     ['新闻', 'news'], ['ACM', 'acm'], ['活动', 'activity'], ['工具', 'tool']]) %>

        <br/>
        <%= f.submit "保存修改", class: "btn btn-large btn-primary location" %>

      <% end %>
    </div>
  </div>
  <%= render 'shared/tips' %>
  <!-- 清除浮动 -->
  <div class="class"></div>
</div>

app/views/posts/index.html.erb
<!-- 搜索出来的内容 -->
<!-- 
<% if @posts.empty? %>
	<p>没有找到您要寻找的内容</p>
<% else %>
	<p>为您找到相关结果 <%= @posts.count %> 个</p>
	<ol class="posts">
		<% @posts.each do |post| %>
			<li>
				<span class="title"><%= link_to post.title, post %></span>                -->
        <!-- 内容过长显示前80个字符 -->
        <!-- 
        <span><%= truncate(strip_tags(post.content), length: 80) %></span>
				<span class="timestamp">
					<%= time_ago_in_words(post.created_at) %> ago.
				</span>
			</li>
		<% end %>
		<div class="line"></div>
	</ol>
<% end %>
-->

<!-- 搜索到的结果高亮显示 -->
<!-- <% content_for :template_js do %>
  <script>
    function getParameterByName(name) {
      name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
      var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
      results = regex.exec(location.search);
      return results == null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
    }
    param = getParameterByName("search");
    if (param != "") {
      str = "<span> </span>".replace(" ", param);
      $(".episode_intro").each(function() {
           newtext = $(this).html().replace(param, str);
           $(this).html(newtext).find("span").css("color", "red");
      });
    }
  </script>
<% end %> -->

app/views/posts/new.html.erb
<div id="page_main">
	<div class="post_main">
		<div class="post_title">
			<%= form_for(@post) do |f| %>
				
				<%= f.label :title, "主题" %>
				<%= f.text_field :title, class: "input-xxlarge" %>

				<%= f.label :content, "内容" %>
				<%= f.text_area :content, class: "textarea" %>

				<br/>
				<%= f.submit "分享笔记", class: "btn btn-large btn-primary location" %>

			<% end %>
		</div>
	</div>
	<%= render 'shared/tips' %>
	<!-- 清除浮动 -->
	<div class="class"></div>
</div>

app/views/posts/post_kind.html.erb
<div class="kind">
	<ul>
		<li><%= link_to "笔记", controller: 'posts', action: 'post_kind', kind: "node" %></li>
		<li><%= link_to "随笔", controller: 'posts', action: 'post_kind', kind: "suibi" %></li>
		<li><%= link_to "博客", controller: 'posts', action: 'post_kind', kind: "blog" %></li>
		<li><%= link_to "日志", controller: 'posts', action: 'post_kind', kind: "log" %></li>
		<li class="choose">文章类型</li>
		<li><%= link_to "工具", controller: 'posts', action: 'post_kind', kind: "tool" %></li>
		<li><%= link_to "ACM", controller: 'posts', action: 'post_kind', kind: "acm" %></li>
		<li><%= link_to "新闻", controller: 'posts', action: 'post_kind', kind: "news" %></li>
		<li><%= link_to "活动", controller: 'posts', action: 'post_kind', kind: "activity" %></li>
	</ul>
</div>

app/views/posts/show.html.erb
<div id="page_main">
	<div class="post_main">
		<div class="post_title clearfix">
			<div class="post_top">
				<!-- 文章标题 -->
				<h2><%= @post.title %></h2>
				<!-- 显示用户上传头像，否则显示默认头像 -->
				<span class="user_avatar">
					<%= @post.user.avatar? ? image_tag(@user.avatar_url(:thumb)) : image_tag("uu.jpg", :height => '100', :width => '100') %>
				</span>
				<!-- 清除浮动 -->
				<div class="class"></div>
			</div>
			<div class="post_totle_font">
				<%= @post.user.name %> • 于 
				<%= time_ago_in_words(@post.created_at) %> 发布
				<% if @comments.any? %>
			 		• 最后由 
			 		<%= @comments.last.commenter %>  于 
			 		<%= time_ago_in_words(@comments.last.created_at) %> 回复
			 	<% end %>
			 	  • <%= @post.viewed_count %> 次阅读
			</div>
			<div class="line"></div>
			<!-- 文章内容 -->
			<div class="post_content">
				<%= wrap(markdown(@post.content)) %>
			</div>
			<!-- 文章功能栏 -->
			<div class="post_shop">
				<!-- 赞功能 -->
				<span>
					<%= topic_function_tag(@post, 'zan_topic_ids', '赞', '已赞') %>
				</span>
				<!-- 收藏文章功能 -->
				<span>
					<%= topic_function_tag(@post, 'favorite_topic_ids', '收藏', '取消收藏') %>
				</span>
				<!-- 删除编辑功能(只有发表文章本人和管理员可见) -->
				<% if current_user?(@post.user) || current_user.admin? %>
				<%= link_to "编辑", edit_post_path(@post) %>
				<%= link_to "删除", @post, method: :delete,
                                     data: { confirm: "确定要删除吗?" },
                                     title: @post.content %>
        <% end %>
     	</div>
		</div>
	</div>

	<%= render 'shared/tips' %>

	<!-- 清除浮动 -->
	<div class="class"></div>

	<!-- 文章所有评论 -->
	<div class="comment">
		<% if @comments.empty? %>
			<h3>还没有回复哦</h3>
		<% else %>
			<div class="comment_number">
				共收到 <%= @comments.count %> 条回复
			</div>
			<div class="line"></div>
			<% @comments.each do |comment| %>
				<div class="comment_content">
					<div class="comment_commenter"><%= comment.commenter %></div>
					<%= wrap(markdown(comment.body)) %> 
					<div class="comment_shop">
						<% if current_user?(comment.user) || current_user.admin? %>
							<%= link_to "编辑", edit_post_comment_path(@post, comment) %>
						<% end %>
					</div>
				</div>
				<div class="line"></div>
			<% end %>
		<% end %>
	</div>

	<!-- 创建评论 -->
	<div class="reply_post">
		<div class="reply_main">
			<% if signed_in? %>
				<%= form_for([@post, @comment]) do |f| %>

					<%= f.label :body, "添加回复" %>
					<%= f.text_area :body, class: "textarea" %> </br>

					<%= f.submit "回复", class: "btn btn-large btn-primary" %>
					<p>请尽量让自己的回复能够对别人有帮助</p>
				<% end %>
			<% else %>
				需要 <%= link_to "登陆", signin_path %> 后回复方可回复, 
				如果你还没有账号你可以 <%= link_to "注册", signup_path %> 一个帐号。
			<% end %>
		</div>
	</div>
</div>