config/routes.rb
Node::Application.routes.draw do

  # 首页
  root to: 'static_pages#home'
  
  # github登录
  match "/auth/:provider/callback", :to => 'omniauths#create'

  #发布内容，评论
  resources :posts do
    # 评论
    resources :comments

    member do
      # 文章收藏功能
      # get :favorite
      # 赞功能
      # get :zan
      # 文章收藏，赞功能
      get :topic_function
    end
    
    # 标签
    collection do
      # 文章种类
      get 'post_kind'
    end

  end 

  # 用户关系
  resources :relationships, only: [ :create, :destroy ]

  # 用户登录
  resources :sessions, only: [ :new, :create, :destroy ]
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  # 首页登录出错跳转
  match '/sessions', to: 'sessions#new'
  
  # 找回密码
  resources :password_resets
  # 重置密码
  get 'password_resets/new'
  

  # 站内通知
  resources :notifications 

  # 管理员功能
  namespace :admins do
    resources :users
  end 

  # 用户系统
  resources :users do

    member do
      # 用户关注
      get :following, :followers
      # 文章收藏(喜爱)
      get :favorite
      # 签到
      get :qiandao
      get :qiandao_execute
      # 设置管理员
      get :set_admin
    end

    collection do
      # qq登录
      get :qqlogin
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
     <%= link_to "NOTE",   '#' %>
     © 2013 NOTE
  </small>
  <nav>
    <ul>
      <li><%= link_to "关于",   '#' %></li>
      <li><%= link_to "联系",   '#' %></li>
      <li><%= link_to "加入",   '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-top">
    <div class="container">
      <div class="header_left">
        <!-- logo -->
        <%= link_to "NOTE", root_path, id: "logo" %>
        <!-- 搜索框 -->
        <div id="seach">
          <%= form_tag posts_path, method: :get do %>
            <div class="input-append pull-right">
              <%= text_field_tag :search, params[:search], class: "span3" %>
              <%= submit_tag "搜索", name: nil, class: "btn" %>
            </div>
          <% end %>
        </div>
      </div>
      <!-- 功能导航 -->
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "首页", root_path %></li>
          <!-- 用户是否登录 -->
          <% if signed_in? %>
            <li><%= link_to "用户", users_path %></li>
            <!-- 管理员列表显示 -->
            <% if current_user.admin? %>
              <li><%= link_to "管理员", admins_users_path %></li>
            <% end %>
            <!-- 站内通知 -->
            <li><%= link_to "#{@unread_count}", notifications_path, :class => "notification_indicator #{'unread' if @unread_count != 0} " %></li>
            <!-- 用户资料设置 -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= @current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "我的主页", current_user %></li>
                <li><%= link_to "个人资料设置", edit_user_path(current_user) %></li>
                <li><%= link_to "我的收藏", favorite_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "退出", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
            <li><%= link_to "分享",  post_kind_posts_path %></li>
            <li><%= link_to "签到", qiandao_user_path(current_user) %></li>
          <% else %>
            <li><%= link_to "登录", signin_path %></li>
            <li><%= link_to "注册", signup_path %></li>
          <% end %>
        </ul>
      </nav>
   </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>share-node</title>
        <%= stylesheet_link_tag    "application", media: "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <!-- 用户信息提示 -->
            <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>

            <%= yield %>

            <!-- 回到顶部 -->
            <div id="go_top" style="display: none;"><%= image_tag("go_top.jpg") %></div>
            <script type="text/javascript">goTopEx();</script>

            <%= render 'layouts/footer' %>
        </div>
    </body>
</html>

app/views/layouts/home_page.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>NODE</title>
    <%= stylesheet_link_tag    "home" %>
    <%= javascript_include_tag "home" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

    <!-- 随机切换背景图片 -->
     <script LANGUAGE="JavaScript">
        // bg = new Array(2); 
        // bg[0] = 'http://www.webjx.com/images/logo.gif'  
        // bg[1] = '.gif'
        // bg[2] = 'http://www.webjx.com/images/12090.gif'
        // index = Math.floor(Math.random() * bg.length);
        // document.write("<BODY BACKGROUND="+bg[index]+">");
     </script> 
</head>
<!-- body中背景图片不起作用 -->
<body style="background-image: url(bg.jpg);">
    <div class="home_main">

        <div id="home_logo">
            <h1>NODE</h1>
        </div>

        <div class="home_welcome">
            欢迎来到 NODE。
            与你关心的人们一起，探寻变化的大千世界。
        </div>

        <div class="home_sign">
            <%= form_tag sessions_path do %>
                <fieldset class="textbox">
                    <%= text_field_tag :email, params[:email], placeholder: '邮件地址' %>
                    <span id="email_verify">X邮件地址不能为空!</span>
                </br>
                    <%= password_field_tag :password, params[:password], placeholder: '密码' %>
                    <span id="pass_verify">X密码不能为空!</span>
                </fieldset>

                <fieldset class="subchck">
                    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
                    <%= label_tag :remember_me, "记住我" %> <br/>
                    <%= link_to "忘记密码？", "#", class: "reminder" %> 
                    <%= submit_tag "登录", class: "btn btn-large btn-primary" %> </br>
                    <%= link_to "github登录", "/auth/github" %> </br>
                    <%= link_to "qq登录", "/users/qqlogin" %> </br>
                    <%= link_to "注册", signup_path %>
                </fieldset>
            <% end %>
        </div> 
<!-- 
        <div class="home_sign">
            <fieldset class="textbox">
                <%= text_field_tag :name, params[:name], placeholder: '用户名' %>
            </br>
                <%= text_field_tag :email, params[:email], placeholder: '邮件地址' %>
            </br>
                <%= password_field_tag :password, params[:password], placeholder: '密码' %>
            </br>
                <%= password_field_tag :password_confirmation, params[:password_confirmation], placeholder: '密码确认' %>
            </fieldset>

            <fieldset class="subchck">
                <%= check_box_tag :remember_me, 1, params[:remember_me] %>
                <span class="reminder">下次自动登录</span>
                <%= submit_tag "创建我的帐号", class: "btn" %>
            </fieldset>
        </div> -->

        <!-- <div>
            目前共有 0 位童鞋加入了! 新版要来啦！
        </div> -->

    </div>
</body>
</html>